defaults:
  -
    scope:
      path: ""
    values:
      title: "Ka WTF"
exclude:
  - 'package.json'
  - 'README.md'
  - 'webpack.config.js'
  - 'package-lock.json'
  - 'node_modules/'
keep_files:
  - 'assets/srcJS'
plugins: [jekyll-paginate]

paginate: 7
paginate_path: "blog/page:num/"